export type WelcomeKind = 'welcome' | 'exit';
export type GroupWelcomeConfig = {
    enabled: boolean;
    welcomeText: string[];
    exitText: string[];
    welcomeCooldown: number;
};
export type WelcomeInputState = {
    groupId: number;
    userId: string;
    kind: WelcomeKind;
    lines: string[];
    createdAt: string;
};
export declare const DEFAULT_WELCOME_TEXT = "\u6B22\u8FCE\u52A0\u5165\u672C\u7FA4\uFF0C\u8BF7\u9075\u5B88\u7FA4\u89C4";
export declare const DEFAULT_EXIT_TEXT = "\u4E58\u7740\u897F\u98CE\u51FA\u53D1\u54AF~";
export declare const DEFAULT_KICK_TEXT = "\u88AB\u4E00\u811A\u8E39\u4E86\u51FA\u53BB~";
export declare const DEFAULT_BOT_JOIN_TEXT = "===\u673A\u5668\u4EBA\u5DF2\u52A0\u5165\u672C\u7FA4===\n\u4F7F\u7528 #\u7BA1\u7406\u5E2E\u52A9 \u67E5\u770B\u529F\u80FD\u5217\u8868\n==================";
export declare const getWelcomeConfig: (groupId: number) => Promise<GroupWelcomeConfig>;
export declare const setWelcomeConfig: (groupId: number, value: Partial<GroupWelcomeConfig>) => Promise<GroupWelcomeConfig>;
export declare const setWelcomeLines: (groupId: number, kind: WelcomeKind, lines: string[]) => Promise<GroupWelcomeConfig>;
export declare const resetWelcomeLines: (groupId: number, kind: WelcomeKind) => Promise<GroupWelcomeConfig>;
export declare const startWelcomeInput: (groupId: number, userId: string, kind: WelcomeKind) => Promise<WelcomeInputState>;
export declare const getWelcomeInput: (groupId: number, userId: string) => Promise<WelcomeInputState | null>;
export declare const appendWelcomeInputLine: (groupId: number, userId: string, line: string) => Promise<WelcomeInputState | null>;
export declare const finishWelcomeInput: (groupId: number, userId: string) => Promise<WelcomeInputState | null>;
export declare const cancelWelcomeInput: (groupId: number, userId: string) => Promise<void>;
export declare const getWelcomeLines: (config: GroupWelcomeConfig, kind: WelcomeKind) => string[];
export declare const getKickText: () => string;
export declare const getBotJoinText: () => string;
export declare const isWelcomeCooldown: (groupId: number) => Promise<boolean>;
export declare const setWelcomeCooldown: (groupId: number, seconds: number) => Promise<void>;
export declare const formatWelcomeConfig: (kind: WelcomeKind, config: GroupWelcomeConfig) => string;
