import { type EventKeys, type Events } from 'alemonjs';
import { type VerifyState } from '../../model/group/verify';
export declare const getMessageId: (result: unknown) => number | null;
export declare const sendGroupAtText: <T extends EventKeys>(event: Events[T], groupId: number, userId: number, text: string) => Promise<any>;
export declare const sendVerifyPrompt: <T extends EventKeys>(event: Events[T], state: VerifyState, seconds: number) => Promise<number | null>;
export declare const sendVerifyFailPrompt: <T extends EventKeys>(event: Events[T], state: VerifyState) => Promise<number | null>;
export declare const sendVerifySuccess: <T extends EventKeys>(event: Events[T], groupId: number, userId: number) => Promise<any>;
export declare const recallMsg: <T extends EventKeys>(event: Events[T], messageId?: number | null) => Promise<boolean>;
export declare const recallVerifyMsgs: <T extends EventKeys>(event: Events[T], state: VerifyState | null | undefined) => Promise<void>;
export declare const recallLastVerifyPrompt: <T extends EventKeys>(event: Events[T], state: VerifyState) => Promise<VerifyState>;
export declare const isGroupMember: <T extends EventKeys>(event: Events[T], groupId: number, userId: number) => Promise<boolean>;
export declare const finishVerifyWithKick: <T extends EventKeys>(event: Events[T], groupId: number, userId: number, text: string) => Promise<boolean>;
