export type CommandEntry = {
  command: string;
  module: string;
  description: string;
  auth?: 'all' | 'admin' | 'master' | 'owner';
};

export const commandEntries: CommandEntry[] = [
  { command: '#管理帮助', module: 'help', description: '查看通用帮助' },
  { command: '#群组管理帮助', module: 'help', description: '查看群管帮助' },
  { command: '#群管帮助', module: 'help', description: '查看群管帮助' },
  { command: '#香菱信息', module: 'admin/bot-info', description: '查看机器人信息' },
  { command: '#群管信息', module: 'admin/bot-info', description: '查看机器人信息' },
  { command: '#机器人信息', module: 'admin/bot-info', description: '查看机器人信息' },
  { command: '#管理版本', module: 'admin/version', description: '查看版本信息' },
  { command: '#管理插件版本', module: 'admin/version', description: '查看插件版本' },
  { command: '#管理插件更新日志', module: 'admin/version', description: '查看迁移更新日志' },
  { command: '#状态', module: 'admin/state', description: '查看运行状态', auth: 'master' },
  { command: '#状态pro', module: 'admin/state', description: '查看运行状态', auth: 'master' },
  { command: '#监控', module: 'admin/state', description: '查看监控信息', auth: 'master' },
  { command: '#状态debug', module: 'admin/state', description: '查看调试状态', auth: 'master' },
  { command: '#原图', module: 'admin/state', description: '发送最近一次状态原图', auth: 'master' },
  { command: '#群管设置', module: 'admin/settings', description: '查看群管设置', auth: 'master' },
  { command: '#群管设置状态开启/关闭', module: 'admin/settings', description: '设置状态图偏好', auth: 'master' },
  { command: '#群管设置渲染精度100', module: 'admin/settings', description: '设置图片渲染精度', auth: 'master' },
  { command: '#管理设置', module: 'admin/notice-settings', description: '查看通知设置', auth: 'master' },
  { command: '#管理设置通知群撤回开启', module: 'admin/notice-settings', description: '设置单个通知项', auth: 'master' },
  { command: '#管理设置通知全部关闭', module: 'admin/notice-settings', description: '一键开关全部通知', auth: 'master' },
  { command: '#指令表', module: 'admin/command-list', description: '查看香菱插件指令表', auth: 'master' },
  { command: '#指令查询 <命令>', module: 'admin/command-list', description: '查询香菱插件命令归属', auth: 'master' },
  { command: '#指令导出 [关键词|全部]', module: 'admin/command-list', description: '导出香菱指令表到 .data', auth: 'master' },
  { command: '#设置日志等级 <level>', module: 'admin/log-level', description: '记录日志等级设置', auth: 'master' },
  { command: '#改头像 <图片>', module: 'admin/bot-manage', description: '尝试通过 OneBot 修改头像', auth: 'master' },
  { command: '#改昵称 <昵称>', module: 'admin/bot-manage', description: '尝试通过 OneBot 修改昵称', auth: 'master' },
  { command: '#改签名 <内容>', module: 'admin/bot-manage', description: '尝试通过 OneBot 修改签名', auth: 'master' },
  { command: '#改状态 <状态>', module: 'admin/bot-manage', description: '尝试通过 OneBot 修改在线状态', auth: 'master' },
  { command: '#改性别 <男|女|无>', module: 'admin/bot-manage', description: '尝试通过 OneBot 修改性别', auth: 'master' },
  { command: '#群列表', module: 'group/group-list', description: '查看群列表', auth: 'master' },
  { command: '#好友列表', module: 'group/friend-list', description: '查看好友列表', auth: 'master' },
  { command: '#群信息 [群号]', module: 'group/group-info', description: '查看群信息', auth: 'master' },
  { command: '#搜索群 <关键词>', module: 'group/search-group', description: '搜索群聊', auth: 'master' },
  { command: '#群员统计', module: 'group/member-stats', description: '统计群成员数量', auth: 'master' },
  { command: '#重载群列表', module: 'group/reload-group-list', description: '刷新群列表缓存', auth: 'master' },
  { command: '#禁言 <@QQ> <时间>', module: 'group/admin-mute', description: '禁言群成员', auth: 'admin' },
  { command: '#解禁 <@QQ>', module: 'group/admin-unmute', description: '解除禁言', auth: 'admin' },
  { command: '#踢 <@QQ>', module: 'group/admin-kick', description: '踢出群成员', auth: 'admin' },
  { command: '#踢黑 <@QQ>', module: 'group/admin-kick', description: '踢出并加入黑名单', auth: 'admin' },
  { command: '#全体禁言', module: 'group/admin-whole-ban', description: '开启全员禁言', auth: 'admin' },
  { command: '#全体解禁', module: 'group/admin-whole-ban', description: '关闭全员禁言', auth: 'admin' },
  { command: '#设置管理 <@QQ>', module: 'group/admin-set-admin', description: '设置群管理员', auth: 'owner' },
  { command: '#取消管理 <@QQ>', module: 'group/admin-set-admin', description: '取消群管理员', auth: 'owner' },
  { command: '#改群名片 <@QQ> <名片>', module: 'group/admin-card', description: '修改群名片', auth: 'master' },
  { command: '#修改头衔 <@QQ> <头衔>', module: 'group/admin-title', description: '修改专属头衔', auth: 'owner' },
  { command: '#退群 <群号>', module: 'group/group-leave', description: '退出群聊', auth: 'master' },
  { command: '#批量退群 <群号列表>', module: 'group/batch-leave', description: '批量退出群聊', auth: 'master' },
  { command: '#改群名称 <名称>', module: 'group/group-name', description: '修改群名称', auth: 'admin' },
  { command: '#改群头像 <图片>', module: 'group/group-portrait', description: '修改群头像', auth: 'admin' },
  { command: '#撤回', module: 'group/message-recall', description: '回复消息撤回', auth: 'admin' },
  { command: '#加精', module: 'group/essence-message', description: '回复消息设精', auth: 'admin' },
  { command: '#设精', module: 'group/essence-message', description: '回复消息设精', auth: 'admin' },
  { command: '#移精', module: 'group/essence-message', description: '回复消息移精', auth: 'admin' },
  { command: '#禁言列表', module: 'group/mute-list', description: '查看禁言成员', auth: 'admin' },
  { command: '#获取禁言列表', module: 'group/mute-list', description: '查看禁言成员', auth: 'admin' },
  { command: '#查看禁言列表', module: 'group/mute-list', description: '查看禁言成员', auth: 'admin' },
  { command: '#解除全部禁言', module: 'group/mute-list', description: '解除全部成员禁言', auth: 'admin' },
  { command: '#我要自闭 <时间>', module: 'group/self-mute', description: '自我禁言' },
  { command: '#发好友 <QQ> <消息>', module: 'group/send-friend-message', description: '发送好友消息', auth: 'master' },
  { command: '#发群聊 <群号> <消息>', module: 'group/send-group-message', description: '发送群消息', auth: 'master' },
  { command: '#发群列表 <序号1,序号2> <消息>', module: 'group/send-group-list-message', description: '按群列表序号批量发送群消息', auth: 'master' },
  { command: '#发通知 <消息>', module: 'group/send-notice', description: '发送群通知', auth: 'admin' },
  { command: '#取头像 <QQ>', module: 'group/avatar', description: '获取头像' },
  { command: '#取群头像 <群号>', module: 'group/avatar', description: '获取群头像' },
  { command: '#谁是龙王', module: 'group/dragon-king', description: '查看今日龙王' },
  { command: '#删好友 <QQ>', module: 'friend/delete-friend', description: '删除好友', auth: 'master' },
  { command: '#取直链', module: 'tools/image-link', description: '获取图片直链' },
  { command: '#取face', module: 'tools/face', description: '获取表情 ID' },
  { command: '#ocr', module: 'tools/ocr', description: '图片文字识别' },
  { command: '#反馈 <内容>', module: 'admin/feedback', description: '发送反馈' },
  { command: '#反馈列表', module: 'admin/feedback', description: '查看反馈', auth: 'master' },
  { command: '#删除反馈 <识别码>', module: 'admin/feedback', description: '删除指定反馈', auth: 'master' },
  { command: '#清空反馈', module: 'admin/feedback', description: '清空反馈记录', auth: 'master' },
  { command: '#查看好友申请', module: 'request/list-friend', description: '查看好友申请', auth: 'master' },
  { command: '#同意', module: 'request/handle-latest', description: '处理唯一一条待处理申请', auth: 'master' },
  { command: '#拒绝', module: 'request/handle-latest', description: '处理唯一一条待处理申请', auth: 'master' },
  { command: '#同意好友申请 <QQ>', module: 'request/handle-friend', description: '同意指定好友申请', auth: 'master' },
  { command: '#拒绝好友申请 <QQ>', module: 'request/handle-friend', description: '拒绝指定好友申请', auth: 'master' },
  { command: '#同意全部好友申请', module: 'request/handle-all', description: '同意全部好友申请', auth: 'master' },
  { command: '#拒绝全部好友申请', module: 'request/handle-all', description: '拒绝全部好友申请', auth: 'master' },
  { command: '#回复 <QQ> <消息>', module: 'request/reply', description: '回复好友私聊', auth: 'master' },
  { command: '#加为好友', module: 'request/add-friend', description: '主动加好友能力说明', auth: 'master' },
  { command: '#查看群邀请', module: 'request/list-group', description: '查看群邀请/加群申请', auth: 'master' },
  { command: '#查看加群申请', module: 'request/list-group', description: '查看本群加群申请', auth: 'admin' },
  { command: '#同意群邀请 <群号>', module: 'request/handle-group', description: '同意指定群邀请', auth: 'master' },
  { command: '#拒绝群邀请 <群号>', module: 'request/handle-group', description: '拒绝指定群邀请', auth: 'master' },
  { command: '#同意加群申请 <QQ>', module: 'request/handle-group', description: '同意指定加群申请', auth: 'admin' },
  { command: '#拒绝加群申请 <QQ>', module: 'request/handle-group', description: '拒绝指定加群申请', auth: 'admin' },
  { command: '#同意全部群邀请', module: 'request/handle-all', description: '同意全部群邀请', auth: 'master' },
  { command: '#拒绝全部群邀请', module: 'request/handle-all', description: '拒绝全部群邀请', auth: 'master' },
  { command: '#同意全部加群申请', module: 'request/handle-all', description: '同意当前群全部加群申请', auth: 'admin' },
  { command: '#拒绝全部加群申请', module: 'request/handle-all', description: '拒绝当前群全部加群申请', auth: 'admin' },
  { command: '#查看全部请求', module: 'request/list-all', description: '查看全部请求', auth: 'master' },
  { command: '#新增违禁词', module: 'group/banned-words', description: '添加违禁词', auth: 'admin' },
  { command: '#新增踢违禁词', module: 'group/banned-words', description: '添加触发踢出的违禁词', auth: 'admin' },
  { command: '#新增禁违禁词', module: 'group/banned-words', description: '添加触发禁言的违禁词', auth: 'admin' },
  { command: '#新增撤违禁词', module: 'group/banned-words', description: '添加触发撤回的违禁词', auth: 'admin' },
  { command: '#新增模糊踢违禁词', module: 'group/banned-words', description: '添加模糊匹配踢出违禁词', auth: 'admin' },
  { command: '#新增正则踢违禁词', module: 'group/banned-words', description: '添加正则匹配踢出违禁词', auth: 'admin' },
  { command: '#删除违禁词', module: 'group/banned-words', description: '删除违禁词', auth: 'admin' },
  { command: '#查看违禁词', module: 'group/banned-words', description: '查看违禁词', auth: 'admin' },
  { command: '#违禁词列表', module: 'group/banned-words', description: '查看违禁词列表', auth: 'admin' },
  { command: '#设置违禁词禁言时间 <秒>', module: 'group/banned-words', description: '设置违禁词触发禁言时间', auth: 'admin' },
  { command: '#增加头衔屏蔽词 <词>', module: 'group/banned-words', description: '添加头衔屏蔽词', auth: 'admin' },
  { command: '#减少头衔屏蔽词 <词>', module: 'group/banned-words', description: '删除头衔屏蔽词', auth: 'admin' },
  { command: '#查看头衔屏蔽词', module: 'group/banned-words', description: '查看头衔屏蔽词', auth: 'admin' },
  { command: '#切换头衔屏蔽词匹配模式', module: 'group/banned-words', description: '切换头衔屏蔽词匹配模式', auth: 'admin' },
  { command: '#加黑', module: 'group/lists', description: '添加黑名单', auth: 'master' },
  { command: '#删黑', module: 'group/lists', description: '删除黑名单', auth: 'master' },
  { command: '#加白', module: 'group/lists', description: '添加白名单', auth: 'admin' },
  { command: '#删白', module: 'group/lists', description: '删除白名单', auth: 'admin' },
  { command: '#黑名单列表', module: 'group/lists', description: '查看黑名单列表', auth: 'master' },
  { command: '#白名单列表', module: 'group/lists', description: '查看白名单列表', auth: 'admin' },
  { command: '#查黑', module: 'group/lists', description: '检查当前群黑名单成员', auth: 'master' },
  { command: '#全群查黑', module: 'group/lists', description: '检查所有群黑名单成员', auth: 'master' },
  { command: '#黑名单授权 <QQ>', module: 'group/lists', description: '授权黑名单管理用户', auth: 'master' },
  { command: '#黑名单取消授权 <QQ>', module: 'group/lists', description: '取消黑名单管理授权', auth: 'master' },
  { command: '#黑名单管理列表', module: 'group/lists', description: '查看黑名单授权用户', auth: 'master' },
  { command: '#开启白名单解禁', module: 'group/lists', description: '开启白名单自动解禁', auth: 'admin' },
  { command: '#关闭白名单解禁', module: 'group/lists', description: '关闭白名单自动解禁', auth: 'admin' },
  { command: '#设置欢迎', module: 'group/welcome-settings', description: '设置欢迎消息', auth: 'admin' },
  { command: '#设置退出', module: 'group/welcome-settings', description: '设置退出消息', auth: 'admin' },
  { command: '#查看欢迎', module: 'group/welcome-settings', description: '查看欢迎消息', auth: 'admin' },
  { command: '#查看退出', module: 'group/welcome-settings', description: '查看退出消息', auth: 'admin' },
  { command: '#重置欢迎', module: 'group/welcome-settings', description: '重置欢迎消息', auth: 'admin' },
  { command: '#重置退出', module: 'group/welcome-settings', description: '重置退出消息', auth: 'admin' },
  { command: '#群聊通知帮助', module: 'group/welcome-settings', description: '查看群聊通知帮助', auth: 'admin' },
  { command: '#开启加群通知', module: 'group/group-add-notice', description: '开启加群通知', auth: 'admin' },
  { command: '#关闭加群通知', module: 'group/group-add-notice', description: '关闭加群通知', auth: 'admin' },
  { command: '#查看加群通知', module: 'group/group-add-notice', description: '查看加群通知配置', auth: 'admin' },
  { command: '#启用投票禁言', module: 'group/vote', description: '启用投票禁言', auth: 'admin' },
  { command: '#禁用投票禁言', module: 'group/vote', description: '禁用投票禁言', auth: 'admin' },
  { command: '#启用投票踢人', module: 'group/vote', description: '启用投票踢人', auth: 'admin' },
  { command: '#禁用投票踢人', module: 'group/vote', description: '禁用投票踢人', auth: 'admin' },
  { command: '#投票设置', module: 'group/vote', description: '查看投票设置', auth: 'admin' },
  { command: '#投票设置超时时间 <秒>', module: 'group/vote', description: '设置投票超时时间', auth: 'admin' },
  { command: '#投票设置最低票数 <票数>', module: 'group/vote', description: '设置投票最低票数', auth: 'admin' },
  { command: '#投票设置禁言时间 <秒>', module: 'group/vote', description: '设置投票禁言时间', auth: 'admin' },
  { command: '#启用管理员一票权', module: 'group/vote', description: '开启管理员跟票直接裁决', auth: 'admin' },
  { command: '#禁用管理员一票权', module: 'group/vote', description: '关闭管理员跟票直接裁决', auth: 'admin' },
  { command: '#启用投票管理员', module: 'group/vote', description: '允许对群管理员发起投票', auth: 'admin' },
  { command: '#禁用投票管理员', module: 'group/vote', description: '禁止对群管理员发起投票', auth: 'admin' },
  { command: '#投票禁言 <@QQ>', module: 'group/vote', description: '发起投票禁言' },
  { command: '#投票踢人 <@QQ>', module: 'group/vote', description: '发起投票踢人' },
  { command: '#支持投票 <QQ>', module: 'group/vote', description: '支持指定投票' },
  { command: '#反对投票 <QQ>', module: 'group/vote', description: '反对指定投票' },
  { command: '#定时禁言', module: 'group/scheduled-mute', description: '设置定时禁言', auth: 'admin' },
  { command: '#定时解禁', module: 'group/scheduled-mute', description: '设置定时解禁', auth: 'admin' },
  { command: '#定时禁言任务', module: 'group/scheduled-mute', description: '查看定时禁言任务', auth: 'admin' },
  { command: '#取消定时禁言', module: 'group/scheduled-mute', description: '取消定时禁言任务', auth: 'admin' },
  { command: '#取消定时解禁', module: 'group/scheduled-mute', description: '取消定时解禁任务', auth: 'admin' },
  { command: '#查看验证', module: 'group/verify-settings', description: '查看入群验证状态', auth: 'admin' },
  { command: '#开启验证', module: 'group/verify-settings', description: '开启入群验证', auth: 'admin' },
  { command: '#关闭验证', module: 'group/verify-settings', description: '关闭入群验证', auth: 'admin' },
  { command: '#重新验证 <QQ>', module: 'group/verify-settings', description: '重新验证成员', auth: 'admin' },
  { command: '#重新验证从未发言的人', module: 'group/verify-settings', description: '批量重新验证从未发言成员', auth: 'admin' },
  { command: '#绕过验证 <QQ>', module: 'group/verify-settings', description: '绕过成员验证', auth: 'admin' },
  { command: '#切换验证模式', module: 'group/verify-settings', description: '切换入群验证模式', auth: 'admin' },
  { command: '#设置验证超时时间 <秒>', module: 'group/verify-settings', description: '设置验证超时时间', auth: 'admin' },
  { command: '#查看从未发言的人', module: 'group/activity', description: '查看从未发言成员', auth: 'admin' },
  { command: '#清理从未发言的人', module: 'group/activity', description: '清理从未发言成员', auth: 'admin' },
  { command: '#查看不活跃排行榜', module: 'group/activity', description: '查看不活跃成员', auth: 'admin' },
  { command: '#查看最近入群情况', module: 'group/activity', description: '查看最近入群成员', auth: 'admin' },
  { command: '#查看最近入群记录', module: 'group/activity', description: '查看最近入群记录', auth: 'admin' },
  { command: '谁@我', module: 'group/who-at', description: '查看谁艾特了自己' },
  { command: '谁艾特我', module: 'group/who-at', description: '查看谁艾特了自己' },
  { command: '谁@他', module: 'group/who-at', description: '查看谁艾特了指定成员' },
  { command: '谁艾特他', module: 'group/who-at', description: '查看谁艾特了指定成员' },
  { command: '#清除艾特数据', module: 'group/who-at', description: '清除艾特记录' },
  { command: '#清除全部艾特数据', module: 'group/who-at', description: '清除全部艾特记录' },
  { command: '#查看群聊撤回', module: 'admin/recall-record', description: '查看最近群聊撤回记录', auth: 'master' },
  { command: '#查看好友撤回', module: 'admin/recall-record', description: '查看最近好友撤回记录', auth: 'master' },
  { command: '#查看私聊撤回', module: 'admin/recall-record', description: '查看最近私聊撤回记录', auth: 'master' }
];

export const findCommands = (keyword: string): CommandEntry[] => {
  const normalized = keyword.replace(/^[#＃!！]/, '').toLowerCase();
  return commandEntries.filter(entry => {
    const command = entry.command.replace(/^[#＃!！]/, '').toLowerCase();
    return command.includes(normalized) || entry.module.toLowerCase().includes(normalized) || entry.description.toLowerCase().includes(normalized);
  });
};
