fontColor: "#ceb78b"
fontShadow: "none"
descColor: "#eee"
fontFamily: "'Microsoft YaHei', 'SimHei', Arial, sans-serif"
titleFontSize: "50px"
groupFontSize: "18px"
commandFontSize: "16px"
descFontSize: "13px"
tableFontSize: "14px"
contBgColor: "rgba(43, 52, 61, 0.8)"
contBgBlur: 3
headerBgColor: "rgba(34, 41, 51, .4)"
rowBgColor1: "rgba(34, 41, 51, .2)"
rowBgColor2: "rgba(34, 41, 51, .4)"

